arcturusPrime/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontEnd.urls')),
    path('backend/', include('backEnd.urls')),

]

backEnd/urls.py
from django.urls import include, path
from rest_framework import routers
from backEnd import views

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.

app_name = 'backEnd'

urlpatterns = [
    path('testPage/', views.testView, name='tester'),
    path('ergResultsList/', views.ergResultList, name='ergResultList'),
    path('session_results_json/<int:pk>/', views.session_results_json, name='session_results_json')
]

frontEnd/urls.py
from django.urls import path, include
from frontEnd import views

app_name = 'frontEnd'

urlpatterns = [
    path('', views.loginPage, name='login'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('current-results/', views.currentResults, name='currentResults'),
    path('historic-erg-results/', views.historicErgResults, name='historicErgResults'),
    path('logout/', views.logoutUser, name='logout'),
    path('profile/<int:pk>', views.profilePage, name='profile'),
    path('analysis/', views.analysis, name='analysis'),
    path('athlete-list/', views.athleteList, name='athleteList'),
    path('session/<int:pk>', views.sessionResults, name='sessionResults'),
]

frontEnd/models.py
from django.db import models
from django.contrib.auth.models import User


class Club(models.Model):
    name = models.CharField(max_length=256, null=False)

    def __str__(self):
        return self.name


class Squad(models.Model):
    name = models.CharField(max_length=256, null=False)

    def __str__(self):
        return self.name


class Athlete(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=256, null=False)
    email = models.CharField(max_length=256, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    year_seven_year = models.PositiveIntegerField(null=True) # first year rowing, used to calculate current year group
    club = models.ForeignKey(Club, null=True, on_delete=models.SET_NULL)
    squad = models.ForeignKey(Squad, null=True, blank=True, on_delete=models.SET_NULL)
    active = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Coach(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=256, null=False)
    email = models.CharField(max_length=256, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    club = models.OneToOneField(Club, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.name


class Coordinator(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=256, null=False)
    email = models.CharField(max_length=256, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    club = models.OneToOneField(Club, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.name


class Session_Data(models.Model):
    TYPE = {
        ('rowing','rowing'),
        ('erg','erg'),
        ('running','running'),
        ('swimming','swimming'),
        ('strength','strength'),
        ('active recovery','active recovery'),
        ('bike','bike'),
        ('cross training','cross training'),
    }

    date = models.DateField()
    type = models.CharField(max_length=256, null=True, blank=True, choices=TYPE)
    notes = models.CharField(max_length=256, null=True, blank=True)

    def __str__(self):
        return str(str(self.date) + ' ' + str(self.type))


class Result(models.Model):
     BOAT_CLASS = {
        ('1x','1x'),
        ('2x','2x'),
        ('2-','2-'),
        ('4x', '4x'),
        ('4x+','4x+'),
        ('4-','4-'),
        ('4+','4+'),
        ('8+','8+'),
     }
     session = models.ForeignKey(Session_Data, related_name='results', on_delete=models.CASCADE)
     distance = models.PositiveIntegerField()
     time = models.TimeField()
     crew = models.ManyToManyField(Athlete, related_name='names')
     rate = models.CharField(max_length=20, null=True, blank=True)
     notes = models.CharField(max_length=256, null=True, blank=True)
     piece_number = models.PositiveIntegerField(default=1)
     boat_class = models.CharField(max_length=10, null=True, blank=True, choices=BOAT_CLASS)


class Distance_Data(models.Model):
    BOAT_CLASS = {
        ('1x','1x'),
        ('2x','2x'),
        ('2-','2-'),
        ('4x', '4x'),
        ('4x+','4x+'),
        ('4-','4-'),
        ('4+','4+'),
        ('8+','8+'),
    }
    TYPE = {
        ('rowing','rowing'),
        ('erg','erg'),
        ('running','running'),
        ('swimming','swimming'),
        ('strength','strength'),
        ('active recovery','active recovery'),
        ('bike','bike'),
        ('cross training','cross training'),
    }
    athlete = models.ForeignKey(Athlete, blank=False, null=False, on_delete=models.CASCADE)
    date = models.DateField(null=True, blank=True)
    boat_class = models.CharField(max_length=10, null=True,blank=True, choices=BOAT_CLASS)
    distance = models.PositiveIntegerField()
    time = models.TimeField(blank=True, null=True)
    rate = models.CharField(max_length=20, null=True, blank=True)
    notes = models.CharField(max_length=256, null=True, blank=True)
    type = models.CharField(max_length=256, null=True, blank=True, choices=TYPE)

    def __str__(self):
        return str(str(self.athlete) + ' ' + str(self.type) + ' ' + str(self.date))


class Season_Period(models.Model):
    period = models.CharField(null=False, blank=False, max_length=256)
    season = models.PositiveIntegerField()
    start_date = models.DateField()
    end_date = models.DateField()

    def __str__(self):
        return str(str(self.season) + ' ' + self.period)

frontEnd/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from frontEnd.decorators import unauthenticated_user, restricted
from frontEnd.models import *
from django.contrib.auth.models import Group
from django.db.models import Avg, Count, Min, Sum
from frontEnd.func import avgTime, avgSplit
import json
from django.core.serializers.json import DjangoJSONEncoder

current_season = 2019
season_start_date = Season_Period.objects.filter(season=current_season).filter(period='pre-season').values_list('start_date')[0][0]
season_end_date = Season_Period.objects.filter(season=current_season).filter(period='term one').values_list('end_date')[0][0]

# Create your views here.
@unauthenticated_user
def loginPage(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('frontEnd:dashboard')
        else:
            messages.info(request, 'Login failed- please try again')

    return render(request, 'frontEnd/login.html')


@login_required(login_url='frontEnd:login')
def dashboard(request):


    group = request.user.groups.all()[0]

    context = {
    'group':str(group),
    }

    return render(request, 'frontEnd/dashboard.html', context)


@login_required(login_url='frontEnd:login')
def currentResults(request):

    group = request.user.groups.all()[0]

    sessions = Session_Data.objects.filter(date__gte=season_start_date, date__lte=season_end_date).order_by('-date')

    context = {
    'group':str(group),
    'sessions':sessions,
    'current_season':current_season,
    }

    return render(request, 'frontEnd/current.html', context)


@login_required
def sessionResults(request, pk):


    session_results = {}

    group = request.user.groups.all()[0]

    session_info = Session_Data.objects.get(id=pk)

    session = Result.objects.filter(session__id=pk)

    for distance in session.values_list('distance').order_by('distance').distinct():
        cols = []
        distance_results = {}
        for crew in session.filter(distance=distance[0]).values_list('crew'):
            crew_results_dict = {}
            crew_times = []
            for time in session.filter(distance=distance[0]).filter(crew=crew[0]).order_by('piece_number').values_list('time'):
                crew_times.append(time[0])

            for piece_number in session.filter(distance=distance[0]).filter(crew=crew[0]).values_list('piece_number'):
                if piece_number[0] not in cols:
                    cols.append(piece_number[0])

            crew_average = avgTime(crew_times)
            crew_average_split = avgSplit(crew_average, distance[0])

            crew_results_dict['average']=[crew_average]
            crew_results_dict['average_split']=[crew_average_split]
            crew_results_dict['results']=crew_times

            distance_results[Athlete.objects.get(id=crew[0]).name] = crew_results_dict

        for crew, crew_results in distance_results.items():
            if len(crew_results['results']) < len(cols):
                for i in range(len(cols) - len(crew_results['results'])):
                    crew_results['results'].append('-')

        session_results[distance[0]] = distance_results
    #
    # jsi = json.dumps(session_results, cls=DjangoJSONEncoder)
    #
    # print(jsi)

    context = {
    'group':str(group),
    'session_results':session_results,
    'session':session,
    'cols':cols,
    'session_info':session_info,
    }

    return render(request, 'frontEnd/session.html', context)


@login_required(login_url='frontEnd:login')
def historicErgResults(request):


    group = request.user.groups.all()[0]

    context = {
    'group':str(group),
    }

    return render(request, 'frontEnd/historicErg.html', context)


def logoutUser(request):

    logout(request)

    return redirect('frontEnd:login')


@login_required(login_url='frontEnd:login')
def profilePage(request, pk):

    group = str(request.user.groups.all()[0])

    if group == 'Coordinator' or group == 'Coach':
        id_filter = pk

    elif group == 'Athlete':
        id_filter = request.user.athlete.id

    athlete = Athlete.objects.get(id=id_filter)

    personal_bests = {}
    for distance in Result.objects.filter(crew__id=id_filter).filter(session__type='erg').values_list('distance').order_by('distance').distinct():
        personal_best = Result.objects.filter(crew__id=id_filter).filter(distance=distance[0]).order_by('time')[0]
        personal_bests[distance[0]]=personal_best

    recent_ergs = Result.objects.filter(crew__id=id_filter).order_by('-session__date')[:5]

    distances = {}
    periods = [('{} Season'.format(current_season), season_start_date), ('Lifetime', '2000-01-01')]

    for period in periods:
        period_dict = {}
        query_set = Distance_Data.objects.filter(athlete__id=id_filter).filter(date__gte=period[1])
        for type in query_set.values_list('type').distinct():
            period_dict[type[0]] = query_set.filter(type=type[0]).aggregate(Sum('distance'))['distance__sum']
        distances[period[0]] = period_dict

    session_log = Distance_Data.objects.filter(athlete__id=id_filter).order_by('-date')[:5]

    context = {
    'athlete':athlete,
    'group':group,
    'personal_bests':personal_bests,
    'recent_ergs':recent_ergs,
    'distances':distances,
    'session_log': session_log,
    }

    return render(request, 'frontEnd/profile.html', context)


@login_required(login_url='frontEnd:login')
@restricted(allowed_roles=['Coach', 'Coordinator'])
def analysis(request):

    context = {}

    return render(request, 'frontEnd/analysis.html', context)


@login_required(login_url='frontEnd:login')
@restricted(allowed_roles=['Coach', 'Coordinator'])
def athleteList(request):

    group = request.user.groups.all()[0]
    # The request.user.club.id is being used to stop a users from being able to see results from different school/clubs
    try:
        full_squad = Athlete.objects.filter(active=True).filter(club__id=request.user.coach.club.id).order_by('name')
    except:
        full_squad = Athlete.objects.filter(active=True).filter(club__id=request.user.coordinator.club.id).order_by('name')

    senior_squad = full_squad.filter(year_seven_year__lte=(current_season-3)).order_by('name')
    inter_squad = full_squad.filter(year_seven_year = (current_season-2)).order_by('name')
    junior_squad = full_squad.filter(year_seven_year__gte = (current_season - 1)).order_by('name')

    context = {
    'group':str(group),
    'current_season':current_season,
    'full_squad':full_squad,
    'senior_squad':senior_squad,
    'inter_squad':inter_squad,
    'junior_squad':junior_squad,
    }

    return render(request, 'frontEnd/athleteList.html', context)

frontEnd/templates/frontEnd/analysis.html
{% extends 'base.html' %}

{% block title_block %}Historic Results{% endblock title_block %}


{% block body_block %}

{% if group == "Athlete" %}

  {% include 'frontEnd/navbar_athlete.html' %}

{% else %}

  {% include 'frontEnd/navbar.html' %}

{% endif %}

<div class="container-fluid">
  <h1>Squad analytics will be run through here</h1>
</div>


{% endblock body_block %}

frontEnd/templates/frontEnd/athleteList.html
{% extends 'base.html' %}

{% block title_block %}Historic Results{% endblock title_block %}


{% block body_block %}

  {% include 'frontEnd/navbar.html' %}


<div class="container-fluid">
  <br>
  {% if group == "Coordinator"  %}
  <h1>{{ current_season }} {{ request.user.coordinator.club.name }} Squad</h1>
  {% else %}
  <h1>{{ current_season }} {{ request.user.coach.club.name }} Squad</h1>
  {% endif %}

  <br>

  <div class="row">
    <div class="col-md-4">
      <div class="card card-body">
        <h4>Seniors ({{ senior_squad.count }})</h4>
        <table>
          {% for athlete in senior_squad %}
            <tr>
              <td>
                <a href="{% url 'frontEnd:profile' pk=athlete.id %}">{{ athlete.name }}</a>
              </td>
            </tr>
          {% endfor %}
        </table>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card card-body">
        <h4>Inters ({{ inter_squad.count }})</h4>
        <table>
          {% for athlete in inter_squad %}
            <tr>
              <td>
                <a href="{% url 'frontEnd:profile' pk=athlete.id %}">{{ athlete.name }}</a>
              </td>
            </tr>
          {% endfor %}
        </table>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card card-body">
        <h4>Juniors ({{ junior_squad.count }})</h4>
        <table>
          {% for athlete in junior_squad %}
            <tr>
                <td>
                  <a href="{% url 'frontEnd:profile' pk=athlete.id %}">{{ athlete.name }}</a>
                </td>
            </tr>
          {% endfor %}
        </table>
      </div>
    </div>
  </div>


</div>


{% endblock body_block %}

frontEnd/templates/frontEnd/current.html
{% extends 'base.html' %}

{% block title_block %}Current Results{% endblock title_block %}


{% block body_block %}

{% if group == "Athlete" %}

  {% include 'frontEnd/navbar_athlete.html' %}

{% else %}

  {% include 'frontEnd/navbar.html' %}

{% endif %}

<br>

<div class="container-fluid">
  <h1>{{current_season}} Season Results</h1>
  <br>

  <div class="row">
      <div class="col-md-2">
        <div class="card card-body">

          <table>
            {% for session in sessions %}
            <tr>
              <td>
                <p class="session_date" id="{{session.id}}"><strong>{{session.type|capfirst}}</strong> {{session.date|date:"D d M Y"}}</p>

              </td>

            </tr>
            {% endfor %}
          </table>
        </div>
      </div>

      <div id="results_window" class="col-md-10">

      </div>
  </div>





</div>

{% endblock body_block %}

frontEnd/templates/frontEnd/dash_content_athlete.html
{% load static %}

<br>
<div class="container-fluid">
  <h1>Welcome to the Alpha Build of Project Arcturus Prime</h1>

  <h3>You are currently viewing the athlete user dashboard content</h3>

</div>

frontEnd/templates/frontEnd/dash_content_coach.html
{% load static %}

<br>
<div class="container-fluid">
  <h1>Welcome to the Alpha Build of Project Arcturus Prime</h1>

  <h3>You are currently viewing the coach user dashboard content</h3>

</div>

frontEnd/templates/frontEnd/dashboard.html
{% extends 'base.html' %}
{% block title_block %}Home{% endblock title_block %}


    {% block body_block %}

    {% if group == "Athlete" %}

      {% include 'frontEnd/navbar_athlete.html' %}
      {% include 'frontEnd/dash_content_athlete.html' %}

    {% else %}

      {% include 'frontEnd/navbar.html' %}
      {% include 'frontEnd/dash_content_coach.html' %}

    {% endif %}

    <p class="footer">Find my code on <a href="https://github.com/adammdekoning/arcturusprime">github</a></p>

    {% endblock body_block %}

frontEnd/templates/frontEnd/historicErg.html
{% extends 'base.html' %}
{% load static %}

{% block title_block %}Historic Erg Results{% endblock title_block %}

{% block scripts_block %}

  <script src="{% static 'frontEnd/js/ergData.js' %}" type="text/javascript"></script>

{% endblock scripts_block %}

{% block body_block %}

{% if group == "Athlete" %}

  {% include 'frontEnd/navbar_athlete.html' %}

{% else %}

  {% include 'frontEnd/navbar.html' %}

{% endif %}
  <br>
<div class="container-fluid">
  <h1>Erg Results</h1>
  <br>
  <div id="ergGrid" class="ag-theme-alpine" style="height:800px; width:1300px;">

  </div>
</div>

{% endblock body_block %}

frontEnd/templates/frontEnd/login.html
{% extends 'base.html' %}

{% block title_block %}Arcturus Prime{% endblock title_block %}
{% block body_block %}

<div class="login-page">

  <form class="form-signin" method="POST">
    {% csrf_token %}
    <div class="text-center mb-4">
      <h1 class="h3 mb-3 font-weight-normal">Welcome to Arcturus Prime</h1>
      <p>Please enter your login details to continue</p>
    </div>
    <div class="form-label-group">
      <input class="form-control" type="text" name="username" placeholder="Username...">
    </div>
    <div class="form-label-group">
      <input class="form-control" type="password" name="password" placeholder="Password...">
    </div>
    <button class="btn btn-lg btn-link btn-block" type="submit" value="Login">Sign In</button>

    {% for message in messages %}
    <p id="messages">{{ message }}</p>
    {% endfor %}
  </form>

</div>


{% endblock body_block %}

frontEnd/templates/frontEnd/navbar.html
{% load static %}

<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'frontEnd:dashboard' %}">Arcturus Prime</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class="navbar-nav mr-auto">
        <li><a class="nav-item nav-link" href="{% url 'frontEnd:currentResults' %}">Results</a></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Historic Results
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">On-Water</a>
            <a class="dropdown-item" href="{% url 'frontEnd:historicErgResults' %}">Erg</a>
            <a class="dropdown-item" href="#">Racing</a>
          </div>
        </li>
        <li><a class="nav-item nav-link" href="{% url 'frontEnd:analysis' %}">Analysis</a></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Profiles
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'frontEnd:athleteList' %}">Athlete</a>
            <a class="dropdown-item" href="#">Squad</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Training Programs
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">View Program</a>
            <a class="dropdown-item" href="#">Create Program</a>
          </div>
        </li>
        <span>
          <form class="form my-2 my-lg-0" action="" method="GET">
            <input class="form-control form-control-dark w-100" placeholder="Search..." name="find">
          </form>
        </span>

      </ul>
      <span class="welcome-message">Hello, {{request.user}}</span>
      <a class="logout-button" href="{% url 'frontEnd:logout' %}">Logout</a>
  </nav>

frontEnd/templates/frontEnd/navbar_athlete.html
{% load static %}

<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'frontEnd:dashboard' %}">Arcturus Prime</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class="navbar-nav mr-auto">
        <li><a class="nav-item nav-link" href="{% url 'frontEnd:currentResults' %}">Results</a></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Historic Results
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">On-Water</a>
            <a class="dropdown-item" href="{% url 'frontEnd:historicErgResults' %}">Erg</a>
            <a class="dropdown-item" href="#">Racing</a>
          </div>
        </li>
        <li><a class="nav-item nav-link" href="{% url 'frontEnd:profile' pk=1 %}">My Profile</a></li>

        <span>
          <form class="form my-2 my-lg-0" action="" method="GET">
            <input class="form-control form-control-dark w-100" placeholder="Search..." name="find">
          </form>
        </span>

      </ul>
      <span class="welcome-message">Hello, {{request.user}}</span>
      <a class="logout-button" href="{% url 'frontEnd:logout' %}">Logout</a>
  </nav>

frontEnd/templates/frontEnd/profile.html
{% extends 'base.html' %}
{% load frontEnd_extras %}
{% load humanize %}

{% block title_block %}{{ request.user.athlete.name }} -- Profile{% endblock title_block %}


{% block body_block %}

{% if group == "Athlete" %}
  {% include 'frontEnd/navbar_athlete.html' %}
{% else %}
  {% include 'frontEnd/navbar.html' %}
{% endif %}

<br>
<div class="container-fluid">

  <h1>{{ athlete.name }}</h1>
  <br>

  <div class="row">
    <div class="col-md-2">
      <div class="card card-body">
        <h4>Distances</h4>
        <hr>

        {% for period, types in distances.items %}
          <h5>{{period}}</h5>
            {% for type, distance in types.items %}
              <p><strong>{{type|capfirst}}:</strong> {{distance|intcomma}}m</p>
            {% endfor %}
          <hr>
        {% endfor %}

      </div>

    </div>
    <div class="col-md-10">
      <div class="row">
        <div class="col-md-6">

          <div class="card card-body">
            <h4>Personal Best Scores</h4>

            <table class="table table-striped">
                <thead>
                  <tr>
                    <th>Date</th>
                    <th>Distance</th>
                    <th>Time</th>
                  </tr>
                </thead>

                <tbody>


                  {% for key, value in personal_bests.items %}

                  <tr>
                    <td> {{ value.session.date|date:'j M Y' }}  </td>
                    <td> {{ key|intcomma }} </td>
                    <td> {{ value.time|format_time }} </td>
                  </tr>

                  {% endfor %}

                </tbody>
            </table>
          </div>
        </div>

        <div class="col-md-6">
          <div class="card card-body">
            <h4>Recent Erg Results</h4>

            <table class="table table-striped">
                <thead>
                  <tr>
                    <th>Date</th>
                    <th>Distance</th>
                    <th>Time</th>
                  </tr>
                </thead>

                <tbody>

                  {% for result in recent_ergs %}

                  <tr>
                    <td> {{ result.session.date|date:'j M Y' }}  </td>
                    <td> {{ result.distance|intcomma }} </td>
                    <td> {{ result.time|format_time }} </td>
                  </tr>

                  {% endfor %}
                </tbody>
            </table>
          </div>
        </div>
      </div>
      <br>
      <div class="row">

        <div class="col-md-6">
          <div class="card card-body">
            <h4>Recent Rowing Results</h4>
          </div>
        </div>

        <div class="col-md-6">
          <div class="card card-body">
            <h4>Session Log</h4>

            <table class="table table-striped">
                <thead>
                  <tr>
                    <th>Date</th>
                    <th>Type</th>
                    <th>Boat Class</th>
                    <th>Distance</th>
                    <th>Notes</th>
                  </tr>
                </thead>

                <tbody>

                  {% for log in session_log %}

                  <tr>
                    <td> {{ log.date|date:'j M Y' }}  </td>
                    <td> {{ log.type|capfirst }} </td>
                    <td> {{ log.boat_class }} </td>
                    <td> {{ log.distance|intcomma }} </td>
                    <td> {{ log.notes}} </td>
                  </tr>

                  {% endfor %}
                </tbody>
            </table>

          </div>
        </div>
      </div>
      <br>

      <div class="row">

        <div class="col-md-6">
          <div class="card card-body">
            <h4>Goals</h4>
          </div>
        </div>

        <div class="col-md-6">
          <div class="card card-body">
            <h4>Coach Notes</h4>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock body_block %}